### ISSUE TITLE
Processing Raw Data in C

### ISSUE THREAD

**Issue by ibby89** [dpa99c/cordova-plugin-hello-c#6]
Hi Dave,

I have been looking at your example of a cordova compiler for C via a Cordova plugin. This is new territory for me so please bear with my ignorance on this subject.

I have a question that I hope you might be able to answer: I have a unique challenge in that I want to process some raw data received on my phone via bluetooth, but the processing algorithm is written in C. Based on your example, I'm not sure whether it is possible to do this without somehow importing the data directly into the C code.

Am I mistaken? Would it be possible to import the raw data into my Ionic app and have it processed by something similar to your plugin and then have the output available to my app?

My thanks in advance.

**Comment by dpa99c** [comment]
If the algorithm is written in C, you have 2 options:

- If you have the C source code, you could rewrite the same algorithm in JS and process it in the Ionic app Webview - no C required
- If you don't have the C source code or performance is an issue, then you'll need to pass the raw data to the C library and have it return the result. To do this, you'd need a plugin similar to this one which could pass the input data to the C code and return result to the Ionic app's JS layer.

**Comment by ibby89** [comment]
Thank you for getting back to me so quickly.

The algorithm is under NDA so I want to touch it as little as possible. I think the second option is much preferred. Would this introduce significant lag? I understand that there will be compilation time and this would be device dependant (based on hardware resources) but I’m glad that there is actually a way to do this.

Your advice is much appreciated.

**Comment by dpa99c** [comment]
The compilation is done offline: you'd cross-compile your C code into a static library that is built into the app and called by your plugin code at runtime.

Any runtime lag would be due to the passing through the various layers of code to get your result, i.e. JS -> Java (Android) / Objective-c (iOS) -> C library -> Java (Android) / Objective-c (iOS) -> JS

however in my experience, this presents very little lag (in the order of ~5 to 10ms)

**Comment by ibby89** [comment]
It's a bit of an overwhelming prospect, especially as a novice, but I will try my hand at it and see where I can get.

**Comment by ibby89** [comment]
Dave, would it be possible to let me know how to make the input method available in my application? I can import the plugin into my app but I do not know what methods are available (the structure is quite extensive!).
My thanks.

**Comment by dpa99c** [comment]
If you look in the [test project code](https://github.com/dpa99c/cordova-plugin-hello-c-test/blob/master/www/js/index.js#L8), you can see how this test plugin's methods are called and then trace the calls through the various layers of the plugin.

For example:
- the [plugin's `hello()` method is called](https://github.com/dpa99c/cordova-plugin-hello-c-test/blob/master/www/js/index.js#L14) by the test app project 
- this invokes the plugin's [JS API function](https://github.com/dpa99c/cordova-plugin-hello-c/blob/master/www/helloc.js#L7) which in turn calls down to the native code
- On Android, this [calls the `execute()` Java method with `action="hello"`](https://github.com/dpa99c/cordova-plugin-hello-c/blob/master/src/android/HelloCPlugin.java#L23)
which calls down to the [Java component of the JNI (Java-Native Interface) layer](https://github.com/dpa99c/cordova-plugin-hello-c/blob/master/src/android/HelloCJni.java#L6) which is a Java class defining the interface to the [C component of the JNI layer](https://github.com/dpa99c/cordova-plugin-hello-c/blob/master/src/android/jni/HelloCJni.c#L51) which finally calls the function in the [cross-platform shared C library](https://github.com/dpa99c/cordova-plugin-hello-c/blob/master/src/common/hello.c#L18)
- On iOS, the JS API function calls down to the [Objective-C plugin layer](https://github.com/dpa99c/cordova-plugin-hello-c/blob/master/src/ios/HelloCPlugin.m#L23) which is able to directly call the [cross-platform shared C library](https://github.com/dpa99c/cordova-plugin-hello-c/blob/master/src/common/hello.c#L18) because iOS is C-based.

Hope this helps

**Comment by ibby89** [comment]
This is very very helpful, thank you very much.
So, if I were to modify the Shared Library to compute a simple sum where one of the inputs to the sum is a user-inputted value and have it display the result, I would:

1. Define the sum in the Shared C Library, inlcuding declaring the input variable
2. Make the input variable and sum output available to the Objective-C plugin layer (for iOS)
3. Make the input variable and sum output available to the Android JNI layer and the Java Component of the JNI layer, which should then be called by execute(...hello)

I will do some testing on device today and see if I can make a small application such as the one described above. I think if I am successful, then I will be much more confident that I could take the project.
